version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: runlog
      POSTGRES_PASSWORD: runlog
      POSTGRES_DB: runlog
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data
      #- pg-data:/var/lib/postgresql/data
    restart: unless-stopped
